FROM mysql:5.7

# Set debian default locale to ja_JP.UTF-8
RUN apt-get update && \
    apt-get install -y locales && \
    rm -rf /var/lib/apt/lists/* && \
    echo "ja_JP.UTF-8 UTF-8" > /etc/locale.gen && \
    locale-gen ja_JP.UTF-8
ENV LC_ALL ja_JP.UTF-8

# Set MySQL character
RUN { \
    echo '[mysqld]'; \
    echo 'character-set-server=utf8mb4'; \
    echo 'collation-server=utf8mb4_general_ci'; \
    echo '[client]'; \
    echo 'default-character-set=utf8mb4'; \
} > /etc/mysql/conf.d/charset.cnf

# Create database
RUN { \
    echo 'CREATE DATABASE IF NOT EXISTS rails_boilerplate_test;'; \
    echo 'CREATE DATABASE IF NOT EXISTS rails_boilerplate_development;'; \
    echo 'GRANT ALL PRIVILEGES ON rails_boilerplate_test.* TO `rails_boilerplate`@`%`;'; \
    echo 'GRANT ALL PRIVILEGES ON rails_boilerplate_development.* TO `rails_boilerplate`@`%`;'; \
} > /docker-entrypoint-initdb.d/init.sql
