version: '3'
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile-MySQL
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_USER=rails_boilerplate
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=root

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && ./wait-for db:3306 -- bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DB_USER=rails_boilerplate
      - DB_PASSWORD=password
      - DB_HOST=db
volumes:
  db-data:
    driver: local
